trainer: classification

$extends$: configs/base_config.yaml

n_temporal_windows: 1
seconds_per_window: 5

$includes$:
  - configs/modality_config.yaml

model: perceiver
model_args:
  latent_num: 16
  latent_dim: 256
  context_dim: 256
  cross_attn_num_heads: 8
  cross_attn_dim_head: 64
  cross_attn_parameter_sharing: true
  self_attn_block_type: "transformer"
  self_attn_num_layers: 3
  self_attn_num_heads: 8
  self_attn_dim_head: 64
  dropout_rate: 0.1
  layer_dropout_rate: 0.0
  self_attn_parameter_sharing: true
