trainer: classification

$extends$: configs/base_config.yaml

$includes$:
  - configs/modality_config.yaml

model: baseline
model_args:
  latent_dim: 256
  num_layers: 4
  self_attn_num_heads: 8
  self_attn_dim_head: 64
  dropout_rate: 0.1
  layer_dropout_rate: 0.0
