trainer: classification

$extends$: configs/base_config.yaml

n_temporal_windows: 1
seconds_per_window: 6

$includes$:
  - configs/modality_config.yaml

evaluators:
  - name: majority_evaluator
    args:
      num_eval_runs: 10
      dataset: e-daic-woz
      kind: validation

model: baseline
model_args:
  latent_dim: 256
  num_layers: 8
  self_attn_num_heads: 4
  self_attn_dim_head: 64
  dropout_rate: 0.1
  layer_dropout_rate: 0.0

losses:
  - kind: xe
    name: depression
    target_head: depression
    args:
      num_classes: 2
      weights: [0.6475150476268496, 2.194742360334613] #[control_weight, depr_weight]
