evaluators:
  - name: majority_evaluator
    args:
      num_eval_runs: 10
      dataset: d-vlog
      kind: validation
  
  - name: temporal_evaluator
    args:
      dataset: d-vlog-eval
      kind: validation
