dataset: d-vlog
trainer: auto
evaluators:
  - name: classification
    args: {}

heads:
  - kind: classification
    name: depression
    args:
      num_classes: 2

losses:
  - kind: xe
    name: depression
    target_head: depression
    args:
      num_classes: 2


# TODO sensitivity test
n_temporal_windows: 4
seconds_per_window: 2

modalities:
  - face-landmarks
  # TODO add more ...

batch_size: 2
accumulation_steps: 1

model_checkpoint:
  monitor_quantity: ClassificationEvaluator_acc
  direction: up

epochs: 300
eval_every: 1

scheduler_args:
  start_epoch: 0
  end_epoch: 300
  base_lr: 0.0001
  max_lr:  0.001
  mode: triangular
  step_size_up: 10
  step_size_down: 10

model: perceiver
model_args:
  embedding_size: 256 # TODO
