trainer: classification

$extends$: configs/base_config.yaml

$includes$:
  - configs/modality_config.yaml

model: perceiver
model_args:
  latent_num: 16
  latent_dim: 128
  context_dim: 256
  cross_attn_num_heads: 4
  cross_attn_dim_head: 64
  cross_attn_parameter_sharing: false
  self_attn_block_type: "transformer"
  self_attn_num_layers: 12
  self_attn_num_heads: 4
  self_attn_dim_head: 64
  dropout_rate: 0.1
  layer_dropout_rate: 0.0
  self_attn_parameter_sharing: true
