evaluators:
  - name: majority_evaluator
    args:
      num_eval_runs: 10
      dataset: daic-woz
      kind: validation
  
  - name: temporal_evaluator
    args:
      dataset: daic-woz-eval
      kind: validation
      min_threshold: 0.35
      max_threshold: 0.65
