evaluators:
  # - name: majority_evaluator
  #   args:
  #     num_eval_runs: 10
  #     dataset: original-d-vlog
  #     kind: validation

  - name: temporal_evaluator
    args:
      dataset: original-d-vlog-new-split-eval
      kind: validation
      min_threshold: 0.35
      max_threshold: 0.65
